/*
 * qTip2 - Pretty powerful tooltips - @@vVERSION
 * http://qtip2.com
 *
 * Copyright (c) 2014 Craig Michael Thompson
 * Released under the MIT, GPL licenses
 * http://jquery.org/license
 *
 * Date: Fri Jul 25 2014 01:12 EDT-0400
@@BUILDPROPS */
/*global window: false, jQuery: false, console: false, define: false */
!function(e,t,i){!function(e){"use strict"
"function"==typeof define&&define.amd?define(["jquery"],e):jQuery&&!jQuery.fn.qtip&&e(jQuery)}(function(s){"use strict"
function n(e,t,i,n){this.id=i,this.target=e,this.tooltip=$,this.elements={target:e},this._id=R+"-"+i,this.timers={img:{}},this.options=t,this.plugins={},this.cache={event:{},target:s(),disabled:S,attr:n,onTooltip:S,lastClass:""},this.rendered=this.destroyed=this.disabled=this.waiting=this.hiddenDuringWait=this.positioning=this.triggering=S}function a(e){return e===$||"object"!==s.type(e)}function o(e){return!(s.isFunction(e)||e&&e.attr||e.length||"object"===s.type(e)&&(e.jquery||e.then))}function r(e){var t,i,n,r
return a(e)?S:(a(e.metadata)&&(e.metadata={type:e.metadata}),"content"in e&&(t=e.content,a(t)||t.jquery||t.done?t=e.content={text:i=o(t)?S:t}:i=t.text,"ajax"in t&&(n=t.ajax,r=n&&n.once!==S,delete t.ajax,t.text=function(e,t){var a=i||s(this).attr(t.options.content.attr)||"Loading...",o=s.ajax(s.extend({},n,{context:t})).then(n.success,$,n.error).then(function(e){return e&&r&&t.set("content.text",e),e},function(e,i,s){t.destroyed||0===e.status||t.set("content.text",i+": "+s)})
return r?a:(t.set("content.text",a),o)}),"title"in t&&(a(t.title)||(t.button=t.title.button,t.title=t.title.text),o(t.title||S)&&(t.title=S))),"position"in e&&a(e.position)&&(e.position={my:e.position,at:e.position}),"show"in e&&a(e.show)&&(e.show=e.show.jquery?{target:e.show}:e.show===j?{ready:j}:{event:e.show}),"hide"in e&&a(e.hide)&&(e.hide=e.hide.jquery?{target:e.hide}:{event:e.hide}),"style"in e&&a(e.style)&&(e.style={classes:e.style}),s.each(F,function(){this.sanitize&&this.sanitize(e)}),e)}function l(e,t){for(var i,s=0,n=e,a=t.split(".");n=n[a[s++]];)s<a.length&&(i=n)
return[i||e,a.pop()]}function c(e,t){var i,s,n
for(i in this.checks)for(s in this.checks[i])(n=RegExp(s,"i").exec(e))&&(t.push(n),("builtin"===i||this.plugins[i])&&this.checks[i][s].apply(this.plugins[i]||this,t))}function d(e){return V.concat("").join(e?"-"+e+" ":" ")}function h(i){return i&&{type:i.type,pageX:i.pageX,pageY:i.pageY,target:i.target,relatedTarget:i.relatedTarget,scrollX:i.scrollX||e.pageXOffset||t.body.scrollLeft||t.documentElement.scrollLeft,scrollY:i.scrollY||e.pageYOffset||t.body.scrollTop||t.documentElement.scrollTop}||{}}function u(e,t){return t>0?setTimeout(s.proxy(e,this),t):(e.call(this),i)}function f(e){return this.tooltip.hasClass(te)?S:(clearTimeout(this.timers.show),clearTimeout(this.timers.hide),this.timers.show=u.call(this,function(){this.toggle(j,e)},this.options.show.delay),i)}function p(e){if(this.tooltip.hasClass(te))return S
var t=s(e.relatedTarget),i=t.closest(G)[0]===this.tooltip[0],n=t[0]===this.options.show.target[0]
if(clearTimeout(this.timers.show),clearTimeout(this.timers.hide),this!==t[0]&&"mouse"===this.options.position.target&&i||this.options.hide.fixed&&/mouse(out|leave|move)/.test(e.type)&&(i||n))try{e.preventDefault(),e.stopImmediatePropagation()}catch(a){}else this.timers.hide=u.call(this,function(){this.toggle(S,e)},this.options.hide.delay,this)}function g(e){return this.tooltip.hasClass(te)||!this.options.hide.inactive?S:(clearTimeout(this.timers.inactive),this.timers.inactive=u.call(this,function(){this.hide(e)},this.options.hide.inactive),i)}function v(e){this.rendered&&this.tooltip[0].offsetWidth>0&&this.reposition(e)}function m(e,i,n){s(t.body).delegate(e,(i.split?i:i.join(le+" "))+le,function(){var e=T.api[s.attr(this,X)]
e&&!e.disabled&&n.apply(e,arguments)})}function b(e,i,a){var o,l,c,d,h,u=s(t.body),f=e[0]===t?u:e,p=e.metadata?e.metadata(a.metadata):$,g="html5"===a.metadata.type&&p?p[a.metadata.name]:$,v=e.data(a.metadata.name||"qtipopts")
try{v="string"==typeof v?s.parseJSON(v):v}catch(m){}if(d=s.extend(j,{},T.defaults,a,"object"==typeof v?r(v):$,r(g||p)),l=d.position,d.id=i,"boolean"==typeof d.content.text){if(c=e.attr(d.content.attr),d.content.attr===S||!c)return S
d.content.text=c}if(l.container.length||(l.container=u),l.target===S&&(l.target=f),d.show.target===S&&(d.show.target=f),d.show.solo===j&&(d.show.solo=l.container.closest("body")),d.hide.target===S&&(d.hide.target=f),d.position.viewport===j&&(d.position.viewport=l.container),l.container=l.container.eq(0),l.at=new q(l.at,j),l.my=new q(l.my),e.data(R))if(d.overwrite)e.qtip("destroy",!0)
else if(d.overwrite===S)return S
return e.attr(Y,i),d.suppress&&(h=e.attr("title"))&&e.removeAttr("title").attr(se,h).attr("title",""),o=new n(e,d,i,!!c),e.data(R,o),e.one("remove.qtip-"+i+" removeqtip.qtip-"+i,function(){var e;(e=s(this).data(R))&&e.destroy(!0)}),o}function _(e){return e.charAt(0).toUpperCase()+e.slice(1)}function y(e,t){var s,n,a=t.charAt(0).toUpperCase()+t.slice(1),o=(t+" "+_e.join(a+" ")+a).split(" "),r=0
if(be[t])return e.css(be[t])
for(;s=o[r++];)if((n=e.css(s))!==i)return be[t]=s,n}function w(e,t){return Math.ceil(parseFloat(y(e,t)))}function x(e,t){this._ns="tip",this.options=t,this.offset=t.offset,this.size=[t.width,t.height],this.init(this.qtip=e)}function C(e,t){this.options=t,this._ns="-modal",this.init(this.qtip=e)}function k(e,t){this._ns="ie6",this.init(this.qtip=e)}var T,z,q,I,M,j=!0,S=!1,$=null,E="x",H="y",P="width",D="height",A="top",W="left",O="bottom",L="right",N="center",B="flipinvert",Q="shift",F={},R="qtip",Y="data-hasqtip",X="data-qtip-id",V=["ui-widget","ui-tooltip"],G="."+R,J="click dblclick mousedown mouseup mousemove mouseleave mouseenter".split(" "),U=R+"-fixed",Z=R+"-default",K=R+"-focus",ee=R+"-hover",te=R+"-disabled",ie="_replacedByqTip",se="oldtitle",ne={ie:function(){for(var e=3,i=t.createElement("div");(i.innerHTML="<!--[if gt IE "+ ++e+"]><i></i><![endif]-->")&&i.getElementsByTagName("i")[0];);return e>4?e:NaN}(),iOS:parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||S}
z=n.prototype,z._when=function(e){return s.when.apply(s,e)},z.render=function(e){if(this.rendered||this.destroyed)return this
var t,i=this,n=this.options,a=this.cache,o=this.elements,r=n.content.text,l=n.content.title,c=n.content.button,d=n.position,h=("."+this._id+" ",[])
return s.attr(this.target[0],"aria-describedby",this._id),this.tooltip=o.tooltip=t=s("<div/>",{id:this._id,"class":[R,Z,n.style.classes,R+"-pos-"+n.position.my.abbrev()].join(" "),width:n.style.width||"",height:n.style.height||"",tracking:"mouse"===d.target&&d.adjust.mouse,role:"alert","aria-live":"polite","aria-atomic":S,"aria-describedby":this._id+"-content","aria-hidden":j}).toggleClass(te,this.disabled).attr(X,this.id).data(R,this).appendTo(d.container).append(o.content=s("<div />",{"class":R+"-content",id:this._id+"-content","aria-atomic":j})),this.rendered=-1,this.positioning=j,l&&(this._createTitle(),s.isFunction(l)||h.push(this._updateTitle(l,S))),c&&this._createButton(),s.isFunction(r)||h.push(this._updateContent(r,S)),this.rendered=j,this._setWidget(),s.each(F,function(e){var t
"render"===this.initialize&&(t=this(i))&&(i.plugins[e]=t)}),this._unassignEvents(),this._assignEvents(),this._when(h).then(function(){i._trigger("render"),i.positioning=S,i.hiddenDuringWait||!n.show.ready&&!e||i.toggle(j,a.event,S),i.hiddenDuringWait=S}),T.api[this.id]=this,this},z.destroy=function(e){function t(){if(!this.destroyed){this.destroyed=j
var e=this.target,t=e.attr(se)
this.rendered&&this.tooltip.stop(1,0).find("*").remove().end().remove(),s.each(this.plugins,function(e){this.destroy&&this.destroy()}),clearTimeout(this.timers.show),clearTimeout(this.timers.hide),this._unassignEvents(),e.removeData(R).removeAttr(X).removeAttr(Y).removeAttr("aria-describedby"),this.options.suppress&&t&&e.attr("title",t).removeAttr(se),this._unbind(e),this.options=this.elements=this.cache=this.timers=this.plugins=this.mouse=$,delete T.api[this.id]}}return this.destroyed?this.target:(e===j&&"hide"!==this.triggering||!this.rendered?t.call(this):(this.tooltip.one("tooltiphidden",s.proxy(t,this)),!this.triggering&&this.hide()),this.target)},I=z.checks={builtin:{"^id$":function(e,t,i,n){var a=i===j?T.nextid:i,o=R+"-"+a
a!==S&&a.length>0&&!s("#"+o).length?(this._id=o,this.rendered&&(this.tooltip[0].id=this._id,this.elements.content[0].id=this._id+"-content",this.elements.title[0].id=this._id+"-title")):e[t]=n},"^prerender":function(e,t,i){i&&!this.rendered&&this.render(this.options.show.ready)},"^content.text$":function(e,t,i){this._updateContent(i)},"^content.attr$":function(e,t,i,s){this.options.content.text===this.target.attr(s)&&this._updateContent(this.target.attr(i))},"^content.title$":function(e,t,s){return s?(s&&!this.elements.title&&this._createTitle(),this._updateTitle(s),i):this._removeTitle()},"^content.button$":function(e,t,i){this._updateButton(i)},"^content.title.(text|button)$":function(e,t,i){this.set("content."+t,i)},"^position.(my|at)$":function(e,t,i){"string"==typeof i&&(e[t]=new q(i,"at"===t))},"^position.container$":function(e,t,i){this.rendered&&this.tooltip.appendTo(i)},"^show.ready$":function(e,t,i){i&&(!this.rendered&&this.render(j)||this.toggle(j))},"^style.classes$":function(e,t,i,s){this.rendered&&this.tooltip.removeClass(s).addClass(i)},"^style.(width|height)":function(e,t,i){this.rendered&&this.tooltip.css(t,i)},"^style.widget|content.title":function(){this.rendered&&this._setWidget()},"^style.def":function(e,t,i){this.rendered&&this.tooltip.toggleClass(Z,!!i)},"^events.(render|show|move|hide|focus|blur)$":function(e,t,i){this.rendered&&this.tooltip[(s.isFunction(i)?"":"un")+"bind"]("tooltip"+t,i)},"^(show|hide|position).(event|target|fixed|inactive|leave|distance|viewport|adjust)":function(){if(this.rendered){var e=this.options.position
this.tooltip.attr("tracking","mouse"===e.target&&e.adjust.mouse),this._unassignEvents(),this._assignEvents()}}}},z.get=function(e){if(this.destroyed)return this
var t=l(this.options,e.toLowerCase()),i=t[0][t[1]]
return i.precedance?i.string():i}
var ae=/^position\.(my|at|adjust|target|container|viewport)|style|content|show\.ready/i,oe=/^prerender|show\.ready/i
z.set=function(e,t){if(this.destroyed)return this
var n,a=this.rendered,o=S,d=this.options
this.checks
return"string"==typeof e?(n=e,e={},e[n]=t):e=s.extend({},e),s.each(e,function(t,n){if(a&&oe.test(t))return delete e[t],i
var r,c=l(d,t.toLowerCase())
r=c[0][c[1]],c[0][c[1]]=n&&n.nodeType?s(n):n,o=ae.test(t)||o,e[t]=[c[0],c[1],n,r]}),r(d),this.positioning=j,s.each(e,s.proxy(c,this)),this.positioning=S,this.rendered&&this.tooltip[0].offsetWidth>0&&o&&this.reposition("mouse"===d.position.target?$:this.cache.event),this},z._update=function(e,t,i){var n=this,a=this.cache
return this.rendered&&e?(s.isFunction(e)&&(e=e.call(this.elements.target,a.event,this)||""),s.isFunction(e.then)?(a.waiting=j,e.then(function(e){return a.waiting=S,n._update(e,t)},$,function(e){return n._update(e,t)})):e===S||!e&&""!==e?S:(e.jquery&&e.length>0?t.empty().append(e.css({display:"block",visibility:"visible"})):t.html(e),this._waitForContent(t).then(function(e){e.images&&e.images.length&&n.rendered&&n.tooltip[0].offsetWidth>0&&n.reposition(a.event,!e.length)}))):S},z._waitForContent=function(e){var t=this.cache
return t.waiting=j,(s.fn.imagesLoaded?e.imagesLoaded():s.Deferred().resolve([])).done(function(){t.waiting=S}).promise()},z._updateContent=function(e,t){this._update(e,this.elements.content,t)},z._updateTitle=function(e,t){this._update(e,this.elements.title,t)===S&&this._removeTitle(S)},z._createTitle=function(){var e=this.elements,t=this._id+"-title"
e.titlebar&&this._removeTitle(),e.titlebar=s("<div />",{"class":R+"-titlebar "+(this.options.style.widget?d("header"):"")}).append(e.title=s("<div />",{id:t,"class":R+"-title","aria-atomic":j})).insertBefore(e.content).delegate(".qtip-close","mousedown keydown mouseup keyup mouseout",function(e){s(this).toggleClass("ui-state-active ui-state-focus","down"===e.type.substr(-4))}).delegate(".qtip-close","mouseover mouseout",function(e){s(this).toggleClass("ui-state-hover","mouseover"===e.type)}),this.options.content.button&&this._createButton()},z._removeTitle=function(e){var t=this.elements
t.title&&(t.titlebar.remove(),t.titlebar=t.title=t.button=$,e!==S&&this.reposition())},z.reposition=function(i,n){if(!this.rendered||this.positioning||this.destroyed)return this
this.positioning=j
var a,o,r=this.cache,l=this.tooltip,c=this.options.position,d=c.target,h=c.my,u=c.at,f=c.viewport,p=c.container,g=c.adjust,v=g.method.split(" "),m=l.outerWidth(S),b=l.outerHeight(S),_=0,y=0,w=l.css("position"),x={left:0,top:0},C=l[0].offsetWidth>0,k=i&&"scroll"===i.type,T=s(e),z=p[0].ownerDocument,q=this.mouse
if(s.isArray(d)&&2===d.length)u={x:W,y:A},x={left:d[0],top:d[1]}
else if("mouse"===d)u={x:W,y:A},!q||!q.pageX||!g.mouse&&i&&i.pageX?i&&i.pageX||((!g.mouse||this.options.show.distance)&&r.origin&&r.origin.pageX?i=r.origin:(!i||i&&("resize"===i.type||"scroll"===i.type))&&(i=r.event)):i=q,"static"!==w&&(x=p.offset()),z.body.offsetWidth!==(e.innerWidth||z.documentElement.clientWidth)&&(o=s(t.body).offset()),x={left:i.pageX-x.left+(o&&o.left||0),top:i.pageY-x.top+(o&&o.top||0)},g.mouse&&k&&q&&(x.left-=(q.scrollX||0)-T.scrollLeft(),x.top-=(q.scrollY||0)-T.scrollTop())
else{if("event"===d?i&&i.target&&"scroll"!==i.type&&"resize"!==i.type?r.target=s(i.target):i.target||(r.target=this.elements.target):"event"!==d&&(r.target=s(d.jquery?d:this.elements.target)),d=r.target,d=s(d).eq(0),0===d.length)return this
d[0]===t||d[0]===e?(_=ne.iOS?e.innerWidth:d.width(),y=ne.iOS?e.innerHeight:d.height(),d[0]===e&&(x={top:(f||d).scrollTop(),left:(f||d).scrollLeft()})):F.imagemap&&d.is("area")?a=F.imagemap(this,d,u,F.viewport?v:S):F.svg&&d&&d[0].ownerSVGElement?a=F.svg(this,d,u,F.viewport?v:S):(_=d.outerWidth(S),y=d.outerHeight(S),x=d.offset()),a&&(_=a.width,y=a.height,o=a.offset,x=a.position),x=this.reposition.offset(d,x,p),(ne.iOS>3.1&&ne.iOS<4.1||ne.iOS>=4.3&&ne.iOS<4.33||!ne.iOS&&"fixed"===w)&&(x.left-=T.scrollLeft(),x.top-=T.scrollTop()),(!a||a&&a.adjustable!==S)&&(x.left+=u.x===L?_:u.x===N?_/2:0,x.top+=u.y===O?y:u.y===N?y/2:0)}return x.left+=g.x+(h.x===L?-m:h.x===N?-m/2:0),x.top+=g.y+(h.y===O?-b:h.y===N?-b/2:0),F.viewport?(x.adjusted=F.viewport(this,x,c,_,y,m,b),o&&x.adjusted.left&&(x.left+=o.left),o&&x.adjusted.top&&(x.top+=o.top)):x.adjusted={left:0,top:0},this._trigger("move",[x,f.elem||f],i)?(delete x.adjusted,n===S||!C||isNaN(x.left)||isNaN(x.top)||"mouse"===d||!s.isFunction(c.effect)?l.css(x):s.isFunction(c.effect)&&(c.effect.call(l,this,s.extend({},x)),l.queue(function(e){s(this).css({opacity:"",height:""}),ne.ie&&this.style.removeAttribute("filter"),e()})),this.positioning=S,this):this},z.reposition.offset=function(e,i,n){function a(e,t){i.left+=t*e.scrollLeft(),i.top+=t*e.scrollTop()}if(!n[0])return i
var o,r,l,c,d=s(e[0].ownerDocument),h=!!ne.ie&&"CSS1Compat"!==t.compatMode,u=n[0]
do"static"!==(r=s.css(u,"position"))&&("fixed"===r?(l=u.getBoundingClientRect(),a(d,-1)):(l=s(u).position(),l.left+=parseFloat(s.css(u,"borderLeftWidth"))||0,l.top+=parseFloat(s.css(u,"borderTopWidth"))||0),i.left-=l.left+(parseFloat(s.css(u,"marginLeft"))||0),i.top-=l.top+(parseFloat(s.css(u,"marginTop"))||0),o||"hidden"===(c=s.css(u,"overflow"))||"visible"===c||(o=s(u)))
while(u=u.offsetParent)
return o&&(o[0]!==d[0]||h)&&a(o,1),i}
var re=(q=z.reposition.Corner=function(e,t){e=(""+e).replace(/([A-Z])/," $1").replace(/middle/gi,N).toLowerCase(),this.x=(e.match(/left|right/i)||e.match(/center/)||["inherit"])[0].toLowerCase(),this.y=(e.match(/top|bottom|center/i)||["inherit"])[0].toLowerCase(),this.forceY=!!t
var i=e.charAt(0)
this.precedance="t"===i||"b"===i?H:E}).prototype
re.invert=function(e,t){this[e]=this[e]===W?L:this[e]===L?W:t||this[e]},re.string=function(){var e=this.x,t=this.y
return e===t?e:this.precedance===H||this.forceY&&"center"!==t?t+" "+e:e+" "+t},re.abbrev=function(){var e=this.string().split(" ")
return e[0].charAt(0)+(e[1]&&e[1].charAt(0)||"")},re.clone=function(){return new q(this.string(),this.forceY)},z.toggle=function(e,i){var n=this.cache,a=this.options,o=this.tooltip
if(i){if(/over|enter/.test(i.type)&&/out|leave/.test(n.event.type)&&a.show.target.add(i.target).length===a.show.target.length&&o.has(i.relatedTarget).length)return this
n.event=h(i)}if(this.waiting&&!e&&(this.hiddenDuringWait=j),!this.rendered)return e?this.render(1):this
if(this.destroyed||this.disabled)return this
var r,l,c,d=e?"show":"hide",u=this.options[d],f=(this.options[e?"hide":"show"],this.options.position),p=this.options.content,g=this.tooltip.css("width"),v=this.tooltip.is(":visible"),m=e||1===u.target.length,b=!i||u.target.length<2||n.target[0]===i.target
return(typeof e).search("boolean|number")&&(e=!v),r=!o.is(":animated")&&v===e&&b,l=r?$:!!this._trigger(d,[90]),this.destroyed?this:(l!==S&&e&&this.focus(i),!l||r?this:(s.attr(o[0],"aria-hidden",!e),e?(n.origin=h(this.mouse),s.isFunction(p.text)&&this._updateContent(p.text,S),s.isFunction(p.title)&&this._updateTitle(p.title,S),!M&&"mouse"===f.target&&f.adjust.mouse&&(s(t).bind("mousemove."+R,this._storeMouse),M=j),g||o.css("width",o.outerWidth(S)),this.reposition(i,arguments[2]),g||o.css("width",""),u.solo&&("string"==typeof u.solo?s(u.solo):s(G,u.solo)).not(o).not(u.target).qtip("hide",s.Event("tooltipsolo"))):(clearTimeout(this.timers.show),delete n.origin,M&&!s(G+'[tracking="true"]:visible',u.solo).not(o).length&&(s(t).unbind("mousemove."+R),M=S),this.blur(i)),c=s.proxy(function(){e?(ne.ie&&o[0].style.removeAttribute("filter"),o.css("overflow",""),"string"==typeof u.autofocus&&s(this.options.show.autofocus,o).focus(),this.options.show.target.trigger("qtip-"+this.id+"-inactive")):o.css({display:"",visibility:"",opacity:"",left:"",top:""}),this._trigger(e?"visible":"hidden")},this),u.effect===S||m===S?(o[d](),c()):s.isFunction(u.effect)?(o.stop(1,1),u.effect.call(o,this),o.queue("fx",function(e){c(),e()})):o.fadeTo(90,e?1:0,c),e&&u.target.trigger("qtip-"+this.id+"-inactive"),this))},z.show=function(e){return this.toggle(j,e)},z.hide=function(e){return this.toggle(S,e)},z.focus=function(e){if(!this.rendered||this.destroyed)return this
var t=s(G),i=this.tooltip,n=parseInt(i[0].style.zIndex,10),a=T.zindex+t.length
return i.hasClass(K)||this._trigger("focus",[a],e)&&(n!==a&&(t.each(function(){this.style.zIndex>n&&(this.style.zIndex=this.style.zIndex-1)}),t.filter("."+K).qtip("blur",e)),i.addClass(K)[0].style.zIndex=a),this},z.blur=function(e){return!this.rendered||this.destroyed?this:(this.tooltip.removeClass(K),this._trigger("blur",[this.tooltip.css("zIndex")],e),this)},z.disable=function(e){return this.destroyed?this:("toggle"===e?e=!(this.rendered?this.tooltip.hasClass(te):this.disabled):"boolean"!=typeof e&&(e=j),this.rendered&&this.tooltip.toggleClass(te,e).attr("aria-disabled",e),this.disabled=!!e,this)},z.enable=function(){return this.disable(S)},z._createButton=function(){var e=this,t=this.elements,i=t.tooltip,n=this.options.content.button,a="string"==typeof n,o=a?n:"Close tooltip"
t.button&&t.button.remove(),n.jquery?t.button=n:t.button=s("<a />",{"class":"qtip-close "+(this.options.style.widget?"":R+"-icon"),title:o,"aria-label":o}).prepend(s("<span />",{"class":"ui-icon ui-icon-close",html:"&times;"})),t.button.appendTo(t.titlebar||i).attr("role","button").click(function(t){return i.hasClass(te)||e.hide(t),S})},z._updateButton=function(e){if(!this.rendered)return S
var t=this.elements.button
e?this._createButton():t.remove()},z._setWidget=function(){var e=this.options.style.widget,t=this.elements,i=t.tooltip,s=i.hasClass(te)
i.removeClass(te),te=e?"ui-state-disabled":"qtip-disabled",i.toggleClass(te,s),i.toggleClass("ui-helper-reset "+d(),e).toggleClass(Z,this.options.style.def&&!e),t.content&&t.content.toggleClass(d("content"),e),t.titlebar&&t.titlebar.toggleClass(d("header"),e),t.button&&t.button.toggleClass(R+"-icon",!e)},z._storeMouse=function(e){(this.mouse=h(e)).type="mousemove"},z._bind=function(e,t,i,n,a){var o="."+this._id+(n?"-"+n:"")
t.length&&s(e).bind((t.split?t:t.join(o+" "))+o,s.proxy(i,a||this))},z._unbind=function(e,t){s(e).unbind("."+this._id+(t?"-"+t:""))}
var le="."+R
s(function(){m(G,["mouseenter","mouseleave"],function(e){var t="mouseenter"===e.type,i=s(e.currentTarget),n=s(e.relatedTarget||e.target),a=this.options
t?(this.focus(e),i.hasClass(U)&&!i.hasClass(te)&&clearTimeout(this.timers.hide)):"mouse"===a.position.target&&a.hide.event&&a.show.target&&!n.closest(a.show.target[0]).length&&this.hide(e),i.toggleClass(ee,t)}),m("["+X+"]",J,g)}),z._trigger=function(e,t,i){var n=s.Event("tooltip"+e)
return n.originalEvent=i&&s.extend({},i)||this.cache.event||$,this.triggering=e,this.tooltip.trigger(n,[this].concat(t||[])),this.triggering=S,!n.isDefaultPrevented()},z._bindEvents=function(e,t,n,a,o,r){if(a.add(n).length===a.length){var l=[]
t=s.map(t,function(t){var n=s.inArray(t,e)
return n>-1?(l.push(e.splice(n,1)[0]),i):t}),l.length&&this._bind(n,l,function(e){var t=this.rendered?this.tooltip[0].offsetWidth>0:!1;(t?r:o).call(this,e)})}this._bind(n,e,o),this._bind(a,t,r)},z._assignInitialEvents=function(e){function t(e){return this.disabled||this.destroyed?S:(this.cache.event=h(e),this.cache.target=e?s(e.target):[i],clearTimeout(this.timers.show),this.timers.show=u.call(this,function(){this.render("object"==typeof e||n.show.ready)},n.show.delay),i)}var n=this.options,a=n.show.target,o=n.hide.target,r=n.show.event?s.trim(""+n.show.event).split(" "):[],l=n.hide.event?s.trim(""+n.hide.event).split(" "):[];/mouse(over|enter)/i.test(n.show.event)&&!/mouse(out|leave)/i.test(n.hide.event)&&l.push("mouseleave"),this._bind(a,"mousemove",function(e){this._storeMouse(e),this.cache.onTarget=j}),this._bindEvents(r,l,a,o,t,function(){clearTimeout(this.timers.show)}),(n.show.ready||n.prerender)&&t.call(this,e)},z._assignEvents=function(){var i=this,n=this.options,a=n.position,o=this.tooltip,r=n.show.target,l=n.hide.target,c=a.container,d=a.viewport,h=s(t),u=(s(t.body),s(e)),m=n.show.event?s.trim(""+n.show.event).split(" "):[],b=n.hide.event?s.trim(""+n.hide.event).split(" "):[]
s.each(n.events,function(e,t){i._bind(o,"toggle"===e?["tooltipshow","tooltiphide"]:["tooltip"+e],t,null,o)}),/mouse(out|leave)/i.test(n.hide.event)&&"window"===n.hide.leave&&this._bind(h,["mouseout","blur"],function(e){/select|option/.test(e.target.nodeName)||e.relatedTarget||this.hide(e)}),n.hide.fixed?l=l.add(o.addClass(U)):/mouse(over|enter)/i.test(n.show.event)&&this._bind(l,"mouseleave",function(){clearTimeout(this.timers.show)}),(""+n.hide.event).indexOf("unfocus")>-1&&this._bind(c.closest("html"),["mousedown","touchstart"],function(e){var t=s(e.target),i=this.rendered&&!this.tooltip.hasClass(te)&&this.tooltip[0].offsetWidth>0,n=t.parents(G).filter(this.tooltip[0]).length>0
t[0]===this.target[0]||t[0]===this.tooltip[0]||n||this.target.has(t[0]).length||!i||this.hide(e)}),"number"==typeof n.hide.inactive&&(this._bind(r,"qtip-"+this.id+"-inactive",g),this._bind(l.add(o),T.inactiveEvents,g,"-inactive")),this._bindEvents(m,b,r,l,f,p),this._bind(r.add(o),"mousemove",function(e){if("number"==typeof n.hide.distance){var t=this.cache.origin||{},i=this.options.hide.distance,s=Math.abs;(s(e.pageX-t.pageX)>=i||s(e.pageY-t.pageY)>=i)&&this.hide(e)}this._storeMouse(e)}),"mouse"===a.target&&a.adjust.mouse&&(n.hide.event&&this._bind(r,["mouseenter","mouseleave"],function(e){this.cache.onTarget="mouseenter"===e.type}),this._bind(h,"mousemove",function(e){this.rendered&&this.cache.onTarget&&!this.tooltip.hasClass(te)&&this.tooltip[0].offsetWidth>0&&this.reposition(e)})),(a.adjust.resize||d.length)&&this._bind(s.event.special.resize?d:u,"resize",v),a.adjust.scroll&&this._bind(u.add(a.container),"scroll",v)},z._unassignEvents=function(){var i=[this.options.show.target[0],this.options.hide.target[0],this.rendered&&this.tooltip[0],this.options.position.container[0],this.options.position.viewport[0],this.options.position.container.closest("html")[0],e,t]
this._unbind(s([]).pushStack(s.grep(i,function(e){return"object"==typeof e})))},T=s.fn.qtip=function(e,t,n){var a=(""+e).toLowerCase(),o=$,l=s.makeArray(arguments).slice(1),c=l[l.length-1],d=this[0]?s.data(this[0],R):$
return!arguments.length&&d||"api"===a?d:"string"==typeof e?(this.each(function(){var e=s.data(this,R)
if(!e)return j
if(c&&c.timeStamp&&(e.cache.event=c),!t||"option"!==a&&"options"!==a)e[a]&&e[a].apply(e,l)
else{if(n===i&&!s.isPlainObject(t))return o=e.get(t),S
e.set(t,n)}}),o!==$?o:this):"object"!=typeof e&&arguments.length?i:(d=r(s.extend(j,{},e)),this.each(function(e){var t,n
return n=s.isArray(d.id)?d.id[e]:d.id,n=!n||n===S||n.length<1||T.api[n]?T.nextid++:n,t=b(s(this),n,d),t===S?j:(T.api[n]=t,s.each(F,function(){"initialize"===this.initialize&&this(t)}),t._assignInitialEvents(c),i)}))},s.qtip=n,T.api={},s.each({attr:function(e,t){if(this.length){var i=this[0],n="title",a=s.data(i,"qtip")
if(e===n&&a&&"object"==typeof a&&a.options.suppress)return arguments.length<2?s.attr(i,se):(a&&a.options.content.attr===n&&a.cache.attr&&a.set("content.text",t),this.attr(se,t))}return s.fn["attr"+ie].apply(this,arguments)},clone:function(e){var t=(s([]),s.fn["clone"+ie].apply(this,arguments))
return e||t.filter("["+se+"]").attr("title",function(){return s.attr(this,se)}).removeAttr(se),t}},function(e,t){if(!t||s.fn[e+ie])return j
var i=s.fn[e+ie]=s.fn[e]
s.fn[e]=function(){return t.apply(this,arguments)||i.apply(this,arguments)}}),s.ui||(s["cleanData"+ie]=s.cleanData,s.cleanData=function(e){for(var t,i=0;(t=s(e[i])).length;i++)if(t.attr(Y))try{t.triggerHandler("removeqtip")}catch(n){}s["cleanData"+ie].apply(this,arguments)}),T.version="@@VERSION",T.nextid=0,T.inactiveEvents=J,T.zindex=15e3,T.defaults={prerender:S,id:S,overwrite:j,suppress:j,content:{text:j,attr:"title",title:S,button:S},position:{my:"top left",at:"bottom right",target:S,container:S,viewport:S,adjust:{x:0,y:0,mouse:j,scroll:j,resize:j,method:"flipinvert flipinvert"},effect:function(e,t,i){s(this).animate(t,{duration:200,queue:S})}},show:{target:S,event:"mouseenter",effect:j,delay:90,solo:S,ready:S,autofocus:S},hide:{target:S,event:"mouseleave",effect:j,delay:0,fixed:S,inactive:S,leave:"window",distance:S},style:{classes:"",widget:S,width:S,height:S,def:j},events:{render:$,move:$,show:$,hide:$,toggle:$,visible:$,hidden:$,focus:$,blur:$}}
var ce,de="margin",he="border",ue="color",fe="background-color",pe="transparent",ge=" !important",ve=!!t.createElement("canvas").getContext,me=/rgba?\(0, 0, 0(, 0)?\)|transparent|#123456/i,be={},_e=["Webkit","O","Moz","ms"]
if(ve)var ye=e.devicePixelRatio||1,we=function(){var e=t.createElement("canvas").getContext("2d")
return e.backingStorePixelRatio||e.webkitBackingStorePixelRatio||e.mozBackingStorePixelRatio||e.msBackingStorePixelRatio||e.oBackingStorePixelRatio||1}(),xe=ye/we
else var Ce=function(e,t,i){return"<qtipvml:"+e+' xmlns="urn:schemas-microsoft.com:vml" class="qtip-vml" '+(t||"")+' style="behavior: url(#default#VML); '+(i||"")+'" />'}
s.extend(x.prototype,{init:function(e){var t,i
i=this.element=e.elements.tip=s("<div />",{"class":R+"-tip"}).prependTo(e.tooltip),ve?(t=s("<canvas />").appendTo(this.element)[0].getContext("2d"),t.lineJoin="miter",t.miterLimit=1e5,t.save()):(t=Ce("shape",'coordorigin="0,0"',"position:absolute;"),this.element.html(t+t),e._bind(s("*",i).add(i),["click","mousedown"],function(e){e.stopPropagation()},this._ns)),e._bind(e.tooltip,"tooltipmove",this.reposition,this._ns,this),this.create()},_swapDimensions:function(){this.size[0]=this.options.height,this.size[1]=this.options.width},_resetDimensions:function(){this.size[0]=this.options.width,this.size[1]=this.options.height},_useTitle:function(e){var t=this.qtip.elements.titlebar
return t&&(e.y===A||e.y===N&&this.element.position().top+this.size[1]/2+this.options.offset<t.outerHeight(j))},_parseCorner:function(e){var t=this.qtip.options.position.my
return e===S||t===S?e=S:e===j?e=new q(t.string()):e.string||(e=new q(e),e.fixed=j),e},_parseWidth:function(e,t,i){var s=this.qtip.elements,n=he+_(t)+"Width"
return(i?w(i,n):w(s.content,n)||w(this._useTitle(e)&&s.titlebar||s.content,n)||w(s.tooltip,n))||0},_parseRadius:function(e){var t=this.qtip.elements,i=he+_(e.y)+_(e.x)+"Radius"
return ne.ie<9?0:w(this._useTitle(e)&&t.titlebar||t.content,i)||w(t.tooltip,i)||0},_invalidColour:function(e,t,i){var s=e.css(t)
return!s||i&&s===e.css(i)||me.test(s)?S:s},_parseColours:function(e){var t=this.qtip.elements,i=this.element.css("cssText",""),n=he+_(e[e.precedance])+_(ue),a=this._useTitle(e)&&t.titlebar||t.content,o=this._invalidColour,r=[]
return r[0]=o(i,fe)||o(a,fe)||o(t.content,fe)||o(t.tooltip,fe)||i.css(fe),r[1]=o(i,n,ue)||o(a,n,ue)||o(t.content,n,ue)||o(t.tooltip,n,ue)||t.tooltip.css(n),s("*",i).add(i).css("cssText",fe+":"+pe+ge+";"+he+":0"+ge+";"),r},_calculateSize:function(e){var t,i,s,n=e.precedance===H,a=this.options.width,o=this.options.height,r="c"===e.abbrev(),l=(n?a:o)*(r?.5:1),c=Math.pow,d=Math.round,h=Math.sqrt(c(l,2)+c(o,2)),u=[this.border/l*h,this.border/o*h]
return u[2]=Math.sqrt(c(u[0],2)-c(this.border,2)),u[3]=Math.sqrt(c(u[1],2)-c(this.border,2)),t=h+u[2]+u[3]+(r?0:u[0]),i=t/h,s=[d(i*a),d(i*o)],n?s:s.reverse()},_calculateTip:function(e,t,i){i=i||1,t=t||this.size
var s=t[0]*i,n=t[1]*i,a=Math.ceil(s/2),o=Math.ceil(n/2),r={br:[0,0,s,n,s,0],bl:[0,0,s,0,0,n],tr:[0,n,s,0,s,n],tl:[0,0,0,n,s,n],tc:[0,n,a,0,s,n],bc:[0,0,s,0,a,n],rc:[0,0,s,o,0,n],lc:[s,0,s,n,0,o]}
return r.lt=r.br,r.rt=r.bl,r.lb=r.tr,r.rb=r.tl,r[e.abbrev()]},_drawCoords:function(e,t){e.beginPath(),e.moveTo(t[0],t[1]),e.lineTo(t[2],t[3]),e.lineTo(t[4],t[5]),e.closePath()},create:function(){var e=this.corner=(ve||ne.ie)&&this._parseCorner(this.options.corner)
return(this.enabled=!!this.corner&&"c"!==this.corner.abbrev())&&(this.qtip.cache.corner=e.clone(),this.update()),this.element.toggle(this.enabled),this.corner},update:function(t,i){if(!this.enabled)return this
var n,a,o,r,l,c,d,h,u=this.qtip.elements,f=this.element,p=f.children(),g=this.options,v=this.size,m=g.mimic,b=Math.round
t||(t=this.qtip.cache.corner||this.corner),m===S?m=t:(m=new q(m),m.precedance=t.precedance,"inherit"===m.x?m.x=t.x:"inherit"===m.y?m.y=t.y:m.x===m.y&&(m[t.precedance]=t[t.precedance])),a=m.precedance,t.precedance===E?this._swapDimensions():this._resetDimensions(),n=this.color=this._parseColours(t),n[1]!==pe?(h=this.border=this._parseWidth(t,t[t.precedance]),g.border&&1>h&&!me.test(n[1])&&(n[0]=n[1]),this.border=h=g.border!==j?g.border:h):this.border=h=0,d=this.size=this._calculateSize(t),f.css({width:d[0],height:d[1],lineHeight:d[1]+"px"}),c=t.precedance===H?[b(m.x===W?h:m.x===L?d[0]-v[0]-h:(d[0]-v[0])/2),b(m.y===A?d[1]-v[1]:0)]:[b(m.x===W?d[0]-v[0]:0),b(m.y===A?h:m.y===O?d[1]-v[1]-h:(d[1]-v[1])/2)],ve?(o=p[0].getContext("2d"),o.restore(),o.save(),o.clearRect(0,0,6e3,6e3),r=this._calculateTip(m,v,xe),l=this._calculateTip(m,this.size,xe),p.attr(P,d[0]*xe).attr(D,d[1]*xe),p.css(P,d[0]).css(D,d[1]),this._drawCoords(o,l),o.fillStyle=n[1],o.fill(),o.translate(c[0]*xe,c[1]*xe),this._drawCoords(o,r),o.fillStyle=n[0],o.fill()):(r=this._calculateTip(m),r="m"+r[0]+","+r[1]+" l"+r[2]+","+r[3]+" "+r[4]+","+r[5]+" xe",c[2]=h&&/^(r|b)/i.test(t.string())?8===ne.ie?2:1:0,p.css({coordsize:d[0]+h+" "+(d[1]+h),antialias:""+(m.string().indexOf(N)>-1),left:c[0]-c[2]*+(a===E),top:c[1]-c[2]*+(a===H),width:d[0]+h,height:d[1]+h}).each(function(e){var t=s(this)
t[t.prop?"prop":"attr"]({coordsize:d[0]+h+" "+(d[1]+h),path:r,fillcolor:n[0],filled:!!e,stroked:!e}).toggle(!(!h&&!e)),!e&&t.html(Ce("stroke",'weight="'+2*h+'px" color="'+n[1]+'" miterlimit="1000" joinstyle="miter"'))})),e.opera&&setTimeout(function(){u.tip.css({display:"inline-block",visibility:"visible"})},1),i!==S&&this.calculate(t,d)},calculate:function(e,t){if(!this.enabled)return S
var i,n,a=this,o=this.qtip.elements,r=this.element,l=this.options.offset,c=(o.tooltip.hasClass("ui-widget"),{})
return e=e||this.corner,i=e.precedance,t=t||this._calculateSize(e),n=[e.x,e.y],i===E&&n.reverse(),s.each(n,function(s,n){var r,d,h
n===N?(r=i===H?W:A,c[r]="50%",c[de+"-"+r]=-Math.round(t[i===H?0:1]/2)+l):(r=a._parseWidth(e,n,o.tooltip),d=a._parseWidth(e,n,o.content),h=a._parseRadius(e),c[n]=Math.max(-a.border,s?d:l+(h>r?h:-r)))}),c[e[i]]-=t[i===E?0:1],r.css({margin:"",top:"",bottom:"",left:"",right:""}).css(c),c},reposition:function(e,t,s,n){function a(e,t,i,s,n){e===Q&&d.precedance===t&&h[s]&&d[i]!==N?d.precedance=d.precedance===E?H:E:e!==Q&&h[s]&&(d[t]=d[t]===N?h[s]>0?s:n:d[t]===s?n:s)}function o(e,t,n){d[e]===N?v[de+"-"+t]=g[e]=r[de+"-"+t]-h[t]:(l=r[n]!==i?[h[t],-r[t]]:[-h[t],r[t]],(g[e]=Math.max(l[0],l[1]))>l[0]&&(s[t]-=h[t],g[t]=S),v[r[n]!==i?n:t]=g[e])}if(this.enabled){var r,l,c=t.cache,d=this.corner.clone(),h=s.adjusted,u=t.options.position.adjust.method.split(" "),f=u[0],p=u[1]||u[0],g={left:S,top:S,x:0,y:0},v={}
this.corner.fixed!==j&&(a(f,E,H,W,L),a(p,H,E,A,O),d.string()===c.corner.string()||c.cornerTop===h.top&&c.cornerLeft===h.left||this.update(d,S)),r=this.calculate(d),r.right!==i&&(r.left=-r.right),r.bottom!==i&&(r.top=-r.bottom),r.user=this.offset,(g.left=f===Q&&!!h.left)&&o(E,W,L),(g.top=p===Q&&!!h.top)&&o(H,A,O),this.element.css(v).toggle(!(g.x&&g.y||d.x===N&&g.y||d.y===N&&g.x)),s.left-=r.left.charAt?r.user:f!==Q||g.top||!g.left&&!g.top?r.left+this.border:0,s.top-=r.top.charAt?r.user:p!==Q||g.left||!g.left&&!g.top?r.top+this.border:0,c.cornerLeft=h.left,c.cornerTop=h.top,c.corner=d.clone()}},destroy:function(){this.qtip._unbind(this.qtip.tooltip,this._ns),this.qtip.elements.tip&&this.qtip.elements.tip.find("*").remove().end().remove()}}),ce=F.tip=function(e){return new x(e,e.options.style.tip)},ce.initialize="render",ce.sanitize=function(e){if(e.style&&"tip"in e.style){var t=e.style.tip
"object"!=typeof t&&(t=e.style.tip={corner:t}),/string|boolean/i.test(typeof t.corner)||(t.corner=j)}},I.tip={"^position.my|style.tip.(corner|mimic|border)$":function(){this.create(),this.qtip.reposition()},"^style.tip.(height|width)$":function(e){this.size=[e.width,e.height],this.update(),this.qtip.reposition()},"^content.title|style.(classes|widget)$":function(){this.update()}},s.extend(j,T.defaults,{style:{tip:{corner:j,mimic:S,width:6,height:6,border:j,offset:0}}})
var ke,Te,ze="qtip-modal",qe="."+ze
Te=function(){function e(e){if(s.expr[":"].focusable)return s.expr[":"].focusable
var t,i,n,a=!isNaN(s.attr(e,"tabindex")),o=e.nodeName&&e.nodeName.toLowerCase()
return"area"===o?(t=e.parentNode,i=t.name,e.href&&i&&"map"===t.nodeName.toLowerCase()?(n=s("img[usemap=#"+i+"]")[0],!!n&&n.is(":visible")):!1):/input|select|textarea|button|object/.test(o)?!e.disabled:"a"===o?e.href||a:a}function i(e){d.length<1&&e.length?e.not("body").blur():d.first().focus()}function n(e){if(l.is(":visible")){var t,n=s(e.target),r=a.tooltip,c=n.closest(G)
t=c.length<1?S:parseInt(c[0].style.zIndex,10)>parseInt(r[0].style.zIndex,10),t||n.closest(G)[0]===r[0]||i(n),o=e.target===d[d.length-1]}}var a,o,r,l,c=this,d={}
s.extend(c,{init:function(){return l=c.elem=s("<div />",{id:"qtip-overlay",html:"<div></div>",mousedown:function(){return S}}).hide(),s(t.body).bind("focusin"+qe,n),s(t).bind("keydown"+qe,function(e){a&&a.options.show.modal.escape&&27===e.keyCode&&a.hide(e)}),l.bind("click"+qe,function(e){a&&a.options.show.modal.blur&&a.hide(e)}),c},update:function(t){a=t,d=t.options.show.modal.stealfocus!==S?t.tooltip.find("*").filter(function(){return e(this)}):[]},toggle:function(e,n,o){var d=(s(t.body),e.tooltip),h=e.options.show.modal,u=h.effect,f=n?"show":"hide",p=l.is(":visible"),g=s(qe).filter(":visible:not(:animated)").not(d)
return c.update(e),n&&h.stealfocus!==S&&i(s(":focus")),l.toggleClass("blurs",h.blur),n&&l.appendTo(t.body),l.is(":animated")&&p===n&&r!==S||!n&&g.length?c:(l.stop(j,S),s.isFunction(u)?u.call(l,n):u===S?l[f]():l.fadeTo(parseInt(o,10)||90,n?1:0,function(){n||l.hide()}),n||l.queue(function(e){l.css({left:"",top:""}),s(qe).length||l.detach(),e()}),r=n,a.destroyed&&(a=$),c)}}),c.init()},Te=new Te,s.extend(C.prototype,{init:function(e){var t=e.tooltip
return this.options.on?(e.elements.overlay=Te.elem,t.addClass(ze).css("z-index",T.modal_zindex+s(qe).length),e._bind(t,["tooltipshow","tooltiphide"],function(e,i,n){var a=e.originalEvent
if(e.target===t[0])if(a&&"tooltiphide"===e.type&&/mouse(leave|enter)/.test(a.type)&&s(a.relatedTarget).closest(Te.elem[0]).length)try{e.preventDefault()}catch(o){}else(!a||a&&"tooltipsolo"!==a.type)&&this.toggle(e,"tooltipshow"===e.type,n)},this._ns,this),e._bind(t,"tooltipfocus",function(e,i){if(!e.isDefaultPrevented()&&e.target===t[0]){var n=s(qe),a=T.modal_zindex+n.length,o=parseInt(t[0].style.zIndex,10)
Te.elem[0].style.zIndex=a-1,n.each(function(){this.style.zIndex>o&&(this.style.zIndex-=1)}),n.filter("."+K).qtip("blur",e.originalEvent),t.addClass(K)[0].style.zIndex=a,Te.update(i)
try{e.preventDefault()}catch(r){}}},this._ns,this),e._bind(t,"tooltiphide",function(e){e.target===t[0]&&s(qe).filter(":visible").not(t).last().qtip("focus",e)},this._ns,this),i):this},toggle:function(e,t,s){return e&&e.isDefaultPrevented()?this:(Te.toggle(this.qtip,!!t,s),i)},destroy:function(){this.qtip.tooltip.removeClass(ze),this.qtip._unbind(this.qtip.tooltip,this._ns),Te.toggle(this.qtip,S),delete this.qtip.elements.overlay}}),ke=F.modal=function(e){return new C(e,e.options.show.modal)},ke.sanitize=function(e){e.show&&("object"!=typeof e.show.modal?e.show.modal={on:!!e.show.modal}:i===e.show.modal.on&&(e.show.modal.on=j))},T.modal_zindex=T.zindex-200,ke.initialize="render",I.modal={"^show.modal.(on|blur)$":function(){this.destroy(),this.init(),this.qtip.elems.overlay.toggle(this.qtip.tooltip[0].offsetWidth>0)}},s.extend(j,T.defaults,{show:{modal:{on:S,effect:j,blur:j,stealfocus:j,escape:j}}}),F.viewport=function(i,s,n,a,o,r,l){function c(e,t,i,n,a,o,r,l,c){var d=s[a],u=w[e],_=x[e],y=i===Q,C=u===a?c:u===o?-c:-c/2,k=_===a?l:_===o?-l:-l/2,T=m[a]+b[a]-(p?0:f[a]),z=T-d,q=d+c-(r===P?g:v)-T,I=C-(w.precedance===e||u===w[t]?k:0)-(_===N?l/2:0)
return y?(I=(u===a?1:-1)*C,s[a]+=z>0?z:q>0?-q:0,s[a]=Math.max(-f[a]+b[a],d-I,Math.min(Math.max(-f[a]+b[a]+(r===P?g:v),d+I),s[a],"center"===u?d-C:1e9))):(n*=i===B?2:0,z>0&&(u!==a||q>0)?(s[a]-=I+n,h.invert(e,a)):q>0&&(u!==o||z>0)&&(s[a]-=(u===N?-I:I)+n,h.invert(e,o)),s[a]<m&&-s[a]>q&&(s[a]=d,h=w.clone())),s[a]-d}var d,h,u,f,p,g,v,m,b,_=n.target,y=i.elements.tooltip,w=n.my,x=n.at,C=n.adjust,k=C.method.split(" "),T=k[0],z=k[1]||k[0],q=n.viewport,I=n.container,M=i.cache,j={left:0,top:0}
return q.jquery&&_[0]!==e&&_[0]!==t.body&&"none"!==C.method?(f=I.offset()||j,p="static"===I.css("position"),d="fixed"===y.css("position"),g=q[0]===e?q.width():q.outerWidth(S),v=q[0]===e?q.height():q.outerHeight(S),m={left:d?0:q.scrollLeft(),top:d?0:q.scrollTop()},b=q.offset()||j,("shift"!==T||"shift"!==z)&&(h=w.clone()),j={left:"none"!==T?c(E,H,T,C.x,W,L,P,a,r):0,top:"none"!==z?c(H,E,z,C.y,A,O,D,o,l):0},h&&M.lastClass!==(u=R+"-pos-"+h.abbrev())&&y.removeClass(i.cache.lastClass).addClass(i.cache.lastClass=u),j):j},F.polys={polygon:function(e,t){var i,s,n,a={width:0,height:0,position:{top:1e10,right:0,bottom:0,left:1e10},adjustable:S},o=0,r=[],l=1,c=1,d=0,h=0
for(o=e.length;o--;)i=[parseInt(e[--o],10),parseInt(e[o+1],10)],i[0]>a.position.right&&(a.position.right=i[0]),i[0]<a.position.left&&(a.position.left=i[0]),i[1]>a.position.bottom&&(a.position.bottom=i[1]),i[1]<a.position.top&&(a.position.top=i[1]),r.push(i)
if(s=a.width=Math.abs(a.position.right-a.position.left),n=a.height=Math.abs(a.position.bottom-a.position.top),"c"===t.abbrev())a.position={left:a.position.left+a.width/2,top:a.position.top+a.height/2}
else{for(;s>0&&n>0&&l>0&&c>0;)for(s=Math.floor(s/2),n=Math.floor(n/2),t.x===W?l=s:t.x===L?l=a.width-s:l+=Math.floor(s/2),t.y===A?c=n:t.y===O?c=a.height-n:c+=Math.floor(n/2),o=r.length;o--&&!(r.length<2);)d=r[o][0]-a.position.left,h=r[o][1]-a.position.top,(t.x===W&&d>=l||t.x===L&&l>=d||t.x===N&&(l>d||d>a.width-l)||t.y===A&&h>=c||t.y===O&&c>=h||t.y===N&&(c>h||h>a.height-c))&&r.splice(o,1)
a.position={left:r[0][0],top:r[0][1]}}return a},rect:function(e,t,i,s){return{width:Math.abs(i-e),height:Math.abs(s-t),position:{left:Math.min(e,i),top:Math.min(t,s)}}},_angles:{tc:1.5,tr:7/4,tl:5/4,bc:.5,br:.25,bl:.75,rc:2,lc:1,c:0},ellipse:function(e,t,i,s,n){var a=F.polys._angles[n.abbrev()],o=0===a?0:i*Math.cos(a*Math.PI),r=s*Math.sin(a*Math.PI)
return{width:2*i-Math.abs(o),height:2*s-Math.abs(r),position:{left:e+o,top:t+r},adjustable:S}},circle:function(e,t,i,s){return F.polys.ellipse(e,t,i,i,s)}},F.svg=function(e,i,n){for(var a,o,r,l,c,d,h,u,f,p,g,v=s(t),m=i[0],b=s(m.ownerSVGElement),_=1,y=1,w=!0;!m.getBBox;)m=m.parentNode
if(!m.getBBox||!m.parentNode)return S
a=b.attr("width")||b.width()||parseInt(b.css("width"),10),o=b.attr("height")||b.height()||parseInt(b.css("height"),10)
var x=(parseInt(i.css("stroke-width"),10)||0)/2
switch(x&&(_+=x/a,y+=x/o),m.nodeName){case"ellipse":case"circle":p=F.polys.ellipse(m.cx.baseVal.value,m.cy.baseVal.value,(m.rx||m.r).baseVal.value+x,(m.ry||m.r).baseVal.value+x,n)
break
case"line":case"polygon":case"polyline":for(f=m.points||[{x:m.x1.baseVal.value,y:m.y1.baseVal.value},{x:m.x2.baseVal.value,y:m.y2.baseVal.value}],p=[],u=-1,d=f.numberOfItems||f.length;++u<d;)h=f.getItem?f.getItem(u):f[u],p.push.apply(p,[h.x,h.y])
p=F.polys.polygon(p,n)
break
default:p=m.getBoundingClientRect(),p={width:p.width,height:p.height,position:{left:p.left,top:p.top}},w=!1}return g=p.position,b=b[0],w&&(b.createSVGPoint&&(r=m.getScreenCTM(),f=b.createSVGPoint(),f.x=g.left,f.y=g.top,l=f.matrixTransform(r),g.left=l.x,g.top=l.y),b.viewBox&&(c=b.viewBox.baseVal)&&c.width&&c.height&&(_*=a/c.width,y*=o/c.height)),g.left+=v.scrollLeft(),g.top+=v.scrollTop(),p},F.imagemap=function(e,t,i,n){t.jquery||(t=s(t))
var a,o,r,l,c,d=t.attr("shape").toLowerCase().replace("poly","polygon"),h=s('img[usemap="#'+t.parent("map").attr("name")+'"]'),u=s.trim(t.attr("coords")),f=u.replace(/,$/,"").split(",")
if(!h.length)return S
if("polygon"===d)l=F.polys.polygon(f,i)
else{if(!F.polys[d])return S
for(r=-1,c=f.length,o=[];++r<c;)o.push(parseInt(f[r],10))
l=F.polys[d].apply(this,o.concat(i))}return a=h.offset(),a.left+=Math.ceil((h.outerWidth(S)-h.width())/2),a.top+=Math.ceil((h.outerHeight(S)-h.height())/2),l.position.left+=a.left,l.position.top+=a.top,l}
var Ie,Me='<iframe class="qtip-bgiframe" frameborder="0" tabindex="-1" src="javascript:\'\';"  style="display:block; position:absolute; z-index:-1; filter:alpha(opacity=0); -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";"></iframe>'
s.extend(k.prototype,{_scroll:function(){var t=this.qtip.elements.overlay
t&&(t[0].style.top=s(e).scrollTop()+"px")},init:function(i){var n=i.tooltip
s("select, object").length<1&&(this.bgiframe=i.elements.bgiframe=s(Me).appendTo(n),i._bind(n,"tooltipmove",this.adjustBGIFrame,this._ns,this)),this.redrawContainer=s("<div/>",{id:R+"-rcontainer"}).appendTo(t.body),i.elements.overlay&&i.elements.overlay.addClass("qtipmodal-ie6fix")&&(i._bind(e,["scroll","resize"],this._scroll,this._ns,this),i._bind(n,["tooltipshow"],this._scroll,this._ns,this)),this.redraw()},adjustBGIFrame:function(){var e,t,i=this.qtip.tooltip,s={height:i.outerHeight(S),width:i.outerWidth(S)},n=this.qtip.plugins.tip,a=this.qtip.elements.tip
t=parseInt(i.css("borderLeftWidth"),10)||0,t={left:-t,top:-t},n&&a&&(e="x"===n.corner.precedance?[P,W]:[D,A],t[e[1]]-=a[e[0]]()),this.bgiframe.css(t).css(s)},redraw:function(){if(this.qtip.rendered<1||this.drawing)return this
var e,t,i,s,n=this.qtip.tooltip,a=this.qtip.options.style,o=this.qtip.options.position.container
return this.qtip.drawing=1,a.height&&n.css(D,a.height),a.width?n.css(P,a.width):(n.css(P,"").appendTo(this.redrawContainer),t=n.width(),1>t%2&&(t+=1),i=n.css("maxWidth")||"",s=n.css("minWidth")||"",e=(i+s).indexOf("%")>-1?o.width()/100:0,i=(i.indexOf("%")>-1?e:1)*parseInt(i,10)||t,s=(s.indexOf("%")>-1?e:1)*parseInt(s,10)||0,t=i+s?Math.min(Math.max(t,s),i):t,n.css(P,Math.round(t)).appendTo(o)),this.drawing=0,this},destroy:function(){this.bgiframe&&this.bgiframe.remove(),this.qtip._unbind([e,this.qtip.tooltip],this._ns)}}),Ie=F.ie6=function(e){return 6===ne.ie?new k(e):S},Ie.initialize="render",I.ie6={"^content|style$":function(){this.redraw()}}})}(window,document)



